version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/azureuser1234/devops_project/app.py:/app/app.py
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase